version: "3.9"
services:
  database:
    image: "library/postgres:latest"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
    volumes:
      - half_db:/var/lib/postgresql/data
    restart: always
  bot:
    build: .
    environment:
      - DATABASE_USERNAME=usr
      - DATABASE_PASSWORD=pwd
    restart: always
volumes:
  half_db: